# 1- case_month
**The earlier of month the Clinical Date (date related to the illness or specimen collection) or the Date Received by CDC**

# 2- res_state
**State of residence**

# 3- state_fips_code
**State FIPS code**

# 4- res_county
**County of residence**

# 5- county_fips_code
**County FIPS code**


# 6- age_group
**Age group [0 - 17 years; 18 - 49 years; 50 - 64 years; 65 + years; Unknown; Missing; NA, if value suppressed for privacy protection.]**

# 7- sex
**Sex [Female; Male; Other; Unknown; Missing; NA, if value suppressed for privacy protection.]**

# 8- race
**Race [American Indian/Alaska Native; Asian; Black; Multiple/Other; Native Hawaiian/Other Pacific Islander; White; Unknown; Missing; NA, if value suppressed for privacy protection.]**

# 9- ethnicity
**Ethnicity [Hispanic; Non-Hispanic; Unknown; Missing; NA, if value suppressed for privacy protection.]**

# 10- case_positive_specimen_interval
**Weeks between earliest date and date of first positive specimen collection Number**

# 11- case_onset_interval
**Weeks between earliest date and date of symptom onset. Number**


# 12- process
**Under what process was the case first identified? [Clinical evaluation; Routine surveillance; Contact tracing of case patient; Multiple; Other; Unknown; Missing]**

# 13- exposure_yn
**In the 14 days prior to illness onset, did the patient have any of the following known exposures: domestic travel, international travel, cruise ship or vessel travel as a passenger or crew member, workplace, airport/airplane, adult congregate living facility (nursing, assisted living, or long-term care facility), school/university/childcare center, correctional facility, community event/mass gathering, animal with confirmed or suspected COVID-19, other exposure, contact with a known COVID-19 case? [Yes, Unknown, Missing]**

# 14- current_status
**What is the current status of this person? [Laboratory-confirmed case, Probable case]**

# 15- symptom_status
**What is the symptom status of this person? [Asymptomatic, Symptomatic, Unknown, Missing]**

# 16- hosp_yn
**Was the patient hospitalized? [Yes, No, Unknown, Missing]**

# 17- icu_yn
**Was the patient admitted to an intensive care unit (ICU)? [Yes, No, Unknown, Missing]**

# 18- death_yn
**Did the patient die as a result of this illness? [Yes; No; Unknown; Missing; NA, if value suppressed for privacy protection.]**

# 19- underlying_conditions_yn
**Did the patient have one or more of the underlying medical conditions and risk behaviors: diabetes mellitus, hypertension, severe obesity (BMI>40), cardiovascular disease, chronic renal disease, chronic liver disease, chronic lung disease, other chronic diseases, immunosuppressive condition, autoimmune condition, current smoker, former smoker, substance abuse or misuse, disability, psychological/psychiatric, pregnancy, other. [Yes, No, blank]**

test change

